<?php
declare(strict_types=1);

namespace SlayerBirden\DFCodeGeneration\Generator\Tests\Api;

use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\Parameter;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use SlayerBirden\DFCodeGeneration\Generator\DataProvider\DataProviderInterface;
use SlayerBirden\DFCodeGeneration\Generator\GeneratorInterface;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

final class AddGenerator implements GeneratorInterface
{
    /**
     * @var DataProviderInterface
     */
    private $dataProvider;
    /**
     * @var Environment
     */
    private $twig;

    public function __construct(DataProviderInterface $dataProvider)
    {
        $this->dataProvider = $dataProvider;
        $loader = new FilesystemLoader(__DIR__ . '/Templates');
        $this->twig = new Environment($loader);
    }

    /**
     * @return string
     * @throws \Twig_Error_Loader
     * @throws \Twig_Error_Runtime
     * @throws \Twig_Error_Syntax
     */
    public function generate(): string
    {
        $file = new PhpFile();
        $file->setStrictTypes();
        $file->addComment('This file is generated by SlayerBirden\DFCodeGeneration');

        $namespace = $file->addNamespace($this->getNameSpace());

        $namespace->addUse('codecept\ApiTester');
        $namespace->addUse('Codeception\Util\HttpCode');

        $class = $namespace->addClass('AddCest');

        $class->addMethod('add' . $this->dataProvider->provide()['entityClassName'])
            ->setParameters([
                (new Parameter('I'))->setTypeHint('\codecept\ApiTester'),
            ])
            ->setBody(
                $this->twig->load('Add/add.template.twig')->render($this->dataProvider->provide())
            )
            ->setReturnType('void')
            ->setVisibility(ClassType::VISIBILITY_PUBLIC);

        $class->addMethod('addIncomplete' . $this->dataProvider->provide()['entityClassName'])
            ->setParameters([
                (new Parameter('I'))->setTypeHint('\codecept\ApiTester'),
            ])
            ->setBody(
                $this->twig->load('Add/add.incomplete.template.twig')->render($this->dataProvider->provide())
            )
            ->setReturnType('void')
            ->setVisibility(ClassType::VISIBILITY_PUBLIC);

        $class->addMethod('addInvalid' . $this->dataProvider->provide()['entityClassName'])
            ->setParameters([
                (new Parameter('I'))->setTypeHint('\codecept\ApiTester'),
            ])
            ->setBody(
                $this->twig->load('Add/add.invalid.template.twig')->render($this->dataProvider->provide())
            )
            ->setReturnType('void')
            ->setVisibility(ClassType::VISIBILITY_PUBLIC);

        if ($this->dataProvider->provide()['hasUnique']) {
            $class->addMethod('addNonUnique' . $this->dataProvider->provide()['entityClassName'])
                ->setParameters([
                    (new Parameter('I'))->setTypeHint('\codecept\ApiTester'),
                ])
                ->setBody(
                    $this->twig->load('Add/add.nonunique.template.twig')->render($this->dataProvider->provide())
                )
                ->setReturnType('void')
                ->setVisibility(ClassType::VISIBILITY_PUBLIC);
        }

        return (new PsrPrinter())->printFile($file);
    }

    public function getClassName(): string
    {
        return $this->getNameSpace() . '\\' . 'AddCest';
    }

    public function getFileName(): string
    {
        return sprintf(
            'tests/api/%s/%s/AddCest.php',
            strtolower($this->dataProvider->provide()['moduleName']),
            $this->dataProvider->provide()['refName']
        );
    }

    private function getNameSpace(): string
    {
        return sprintf(
            'codecept\%s\%s',
            strtolower($this->dataProvider->provide()['moduleName']),
            $this->dataProvider->provide()['refName']
        );
    }
}
