language: php

php:
  - "7.2"
  - "7.1"

install: composer install --no-interaction

env:
  global:
  - TMPDIR=$TRAVIS_BUILD_DIR/tmp

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
- mkdir -p $TRAVIS_BUILD_DIR/tmp

script:
  - vendor/bin/phpunit --coverage-clover ./coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover

notifications:
  email: true

matrix:
  fast_finish: true
